const API_BASE = window.VELOURA_API_BASE || (window.location.hostname.includes('localhost') ? 'http://localhost:8787/api' : '/api');
const createVisitorKey = () => typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const state = { products: [], bag: JSON.parse(localStorage.getItem('veloura-bag') || '[]'), filter: 'all', search: '', chatMessages: [], marketingBanners: [], visitorKey: localStorage.getItem('veloura-chat-visitor') || `visitor-${createVisitorKey()}`, adminPreview: new URLSearchParams(window.location.search).get('admin_preview') === '1' && Boolean(sessionStorage.getItem('veloura-admin-token')), adminPreviewMode: sessionStorage.getItem('veloura-admin-mode') === 'edit' ? 'edit' : 'view' };
const money = (value) => `৳${Number(value || 0).toLocaleString('en-BD')}`;
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const icon = (name, className = '') => window.VelouraIcons?.svg(name, className) || '';
localStorage.setItem('veloura-chat-visitor', state.visitorKey);
function track(name, params = {}) { return window.velouraAnalytics?.track ? window.velouraAnalytics.track(name, params) : (window.dataLayer = window.dataLayer || [], window.dataLayer.push({ event: name, ...params })); }
function toast(message) { const node = $('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); }
function saveBag() { localStorage.setItem('veloura-bag', JSON.stringify(state.bag)); renderBag(); }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Could not load shop data'); return data; }
function renderCategories(categories) { $('#category-grid').innerHTML = categories.map((category) => `<a class="category-card" href="#shop" data-category="${escapeHtml(category.slug)}"><img src="${escapeHtml(category.imageUrl || './assets/asset-fallback.svg')}" alt="${escapeHtml(category.name)}" loading="lazy" /><span>${escapeHtml(category.name)} <b>${icon('arrowUpRight')}</b></span></a>`).join(''); document.querySelectorAll('.category-card').forEach((card) => card.addEventListener('click', () => { state.filter = card.dataset.category; document.querySelectorAll('.filter').forEach((filter) => filter.classList.toggle('active', filter.dataset.filter === state.filter)); renderProducts(); renderMarketingBanners(state.marketingBanners); track('category_select', { category: state.filter }); })); }
function searchText(product) { return [product.name, product.description, product.shortDescription, product.categoryName, product.categorySlug, product.sku, product.barcode, product.tagsJson].map((value) => String(value || '').normalize('NFKC').toLocaleLowerCase()).join(' '); }
function visibleProducts() { let products = state.filter === 'featured' ? state.products.filter((product) => product.featured || (Number(product.reviewCount || 0) > 0 && Number(product.rating || 0) >= 4.5)) : state.filter === 'all' ? state.products : state.products.filter((product) => product.categorySlug === state.filter); const terms = state.search.trim().normalize('NFKC').toLocaleLowerCase().split(/\s+/).filter(Boolean); if (terms.length) products = products.filter((product) => { const haystack = searchText(product); return terms.every((term) => haystack.includes(term)); }); const unique = new Map(); products.forEach((product) => { const key = String(product.id ?? product.slug ?? product.name).toLowerCase(); if (!unique.has(key)) unique.set(key, product); }); return Array.from(unique.values()); }
function parseProductBadges(value) { let parsed = []; try { parsed = Array.isArray(value) ? value : JSON.parse(value || '[]'); } catch {} return Array.isArray(parsed) ? parsed.map((item) => String(item).toLowerCase()).filter((item) => ['hot', 'instock', 'new'].includes(item)) : []; }
function productBadges(product) { const labels = { hot: 'Hot Product', instock: 'In Stock', new: 'New Product' }; const selected = parseProductBadges(product.badgesJson || product.badges); if (Number(product.stock || 0) <= 0) selected.push('out'); return Array.from(new Set(selected)).map((badge) => `<span class="product-badge badge-${badge}">${badge === 'out' ? 'Stock out' : labels[badge]}</span>`).join(''); }
function parseProductMedia(product) { let parsed = []; try { parsed = JSON.parse(product.mediaJson || '[]'); } catch {} const media = (Array.isArray(parsed) ? parsed : []).map((item) => ({ type: item?.type === 'video' ? 'video' : 'image', url: typeof item === 'string' ? item : item?.url, alt: item?.alt || product.name })).filter((item) => /^(https:\/\/|\/assets\/|\/media\/)/i.test(String(item.url || ''))); const primary = String(product.imageUrl || '').trim(); if (primary && !media.some((item) => item.url === primary)) media.unshift({ type: 'image', url: primary, alt: product.name }); return media.length ? media : [{ type: 'image', url: './assets/asset-fallback.svg', alt: product.name }]; }
function productCardImage(product) { return parseProductMedia(product).find((item) => item.type === 'image')?.url || './assets/asset-fallback.svg'; }
function renderProducts() { const products = visibleProducts(); $('#product-grid').innerHTML = products.length ? products.map((product) => { const detailHref = new URL(`./product.html?slug=${encodeURIComponent(product.slug || product.id)}${state.adminPreview ? '&admin_preview=1' : ''}`, window.location.href).href; const adminEditLink = state.adminPreview && state.adminPreviewMode === 'edit' ? `<a class="admin-preview-edit" target="_parent" href="./admin/index.html?view=products&edit=${encodeURIComponent(product.id)}">Edit product ${icon('arrowUpRight')}</a>` : ''; return `<article class="product-card"><a class="product-image-wrap product-detail-link" href="${detailHref}"><img class="product-image" src="${escapeHtml(productCardImage(product))}" alt="${escapeHtml(product.name)}" loading="lazy" /><div class="product-badges">${productBadges(product)}</div></a><div class="product-info"><span class="product-category">${escapeHtml(product.categoryName || 'Veloura edit')}${Number(product.rating || 0) ? ` · ${icon('star', 'product-rating-icon')} ${Number(product.rating).toFixed(1)}` : ''}</span><h3 class="product-name"><a class="product-detail-link" href="${detailHref}">${escapeHtml(product.name)}</a></h3><p class="product-description">${escapeHtml(product.description)}</p><div class="product-price"><strong>${money(product.price)}</strong>${product.compareAtPrice ? `<del>${money(product.compareAtPrice)}</del>` : ''}</div><div class="product-actions"><button class="product-quick product-add" data-add="${product.id}" ${product.stock < 1 ? 'disabled' : ''}>Add to Cart ${icon('plus')}</button><button class="product-shop-now" data-add="${product.id}" ${product.stock < 1 ? 'disabled' : ''}>Shop Now ${icon('arrowRight')}</button></div>${adminEditLink}</div></article>`; }).join('') : '<div class="loading">No products in this edit yet.</div>'; document.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); addToBag(Number(button.dataset.add)); if (button.classList.contains('product-shop-now')) toggleDrawer(true); })); }
window.addEventListener('message', (event) => { if (event.origin !== window.location.origin || event.data?.type !== 'veloura-admin-preview-mode' || !state.adminPreview) return; const nextMode = event.data.mode === 'edit' ? 'edit' : 'view'; if (state.adminPreviewMode !== nextMode) { state.adminPreviewMode = nextMode; renderProducts(); } });
function addToBag(productId) { const product = state.products.find((item) => item.id === productId); if (!product) return; const existing = state.bag.find((item) => item.id === productId); const minimum = Math.max(1, Number(product.minOrderQty || 1)); const maximum = Number(product.stock || 0); if (existing) existing.quantity = Math.min(maximum || existing.quantity + 1, existing.quantity + 1); else state.bag.push({ id: product.id, name: product.name, price: product.price, imageUrl: productCardImage(product), quantity: minimum, stock: maximum, minOrderQty: minimum, categoryName: product.categoryName, categorySlug: product.categorySlug }); saveBag(); toast(`${product.name} added to your bag`); track('add_to_cart', { currency: 'BDT', value: Number(product.price || 0) * minimum, items: [window.velouraAnalytics?.item(product, minimum) || { item_id: product.slug, item_name: product.name, price: Number(product.price || 0), quantity: minimum, item_category: product.categoryName || product.categorySlug }] }); }
function removeFromBag(productId) { const item = state.bag.find((entry) => entry.id === productId); state.bag = state.bag.filter((entry) => entry.id !== productId); saveBag(); if (item) track('remove_from_cart', { currency: 'BDT', value: Number(item.price || 0) * Number(item.quantity || 1), items: [window.velouraAnalytics?.item(item, item.quantity) || { item_id: item.id, item_name: item.name, price: Number(item.price || 0), quantity: Number(item.quantity || 1) }] }); }
function changeBagQuantity(productId, direction) { const item = state.bag.find((entry) => Number(entry.id) === Number(productId)); if (!item) return; const minimum = Math.max(1, Number(item.minOrderQty || 1)); const maximum = Number(item.stock || 0); const next = Number(item.quantity || minimum) + direction; if (next < minimum) return removeFromBag(productId); item.quantity = maximum ? Math.min(maximum, next) : next; saveBag(); }
function renderBag() { const totalItems = state.bag.reduce((sum, item) => sum + Number(item.quantity || 0), 0); $('#bag-count').textContent = totalItems; const total = state.bag.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.quantity || 0), 0); $('#bag-total').textContent = money(total); $('#bag-items').innerHTML = state.bag.length ? state.bag.map((item) => `<div class="bag-item"><img src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.name)}" /><div><strong>${escapeHtml(item.name)}</strong><div class="quantity-stepper bag-stepper"><button data-bag-qty="${item.id}" data-direction="-1" aria-label="Decrease ${escapeHtml(item.name)}">${icon('minus')}</button><span>${Number(item.quantity || 0)}</span><button data-bag-qty="${item.id}" data-direction="1" aria-label="Increase ${escapeHtml(item.name)}">${icon('plus')}</button></div><small>${money(item.price)} each</small></div><button data-remove="${item.id}" aria-label="Remove ${escapeHtml(item.name)}">${icon('close')}</button></div>`).join('') : '<div class="bag-empty">Your bag is waiting for a little ritual.</div>'; document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => removeFromBag(Number(button.dataset.remove)))); document.querySelectorAll('[data-bag-qty]').forEach((button) => button.addEventListener('click', () => changeBagQuantity(Number(button.dataset.bagQty), Number(button.dataset.direction)))); }
function toggleDrawer(open) { $('#bag-drawer').classList.toggle('open', open); $('#bag-drawer').setAttribute('aria-hidden', String(!open)); }
function toggleMobileNav(open) { const nav = $('#mobile-nav'); const backdrop = $('#mobile-nav-backdrop'); nav?.classList.toggle('open', open); backdrop?.classList.toggle('open', open); nav?.setAttribute('aria-hidden', String(!open)); backdrop?.setAttribute('aria-hidden', String(!open)); document.body.classList.toggle('menu-open', open); }
function openSearch() { const overlay = $('#search-overlay'); overlay?.classList.add('open'); overlay?.setAttribute('aria-hidden', 'false'); document.body.classList.add('search-open'); window.setTimeout(() => $('#site-search')?.focus(), 60); }
function closeSearch() { const overlay = $('#search-overlay'); overlay?.classList.remove('open'); overlay?.setAttribute('aria-hidden', 'true'); document.body.classList.remove('search-open'); }
function submitSearch(event) { event.preventDefault(); const input = $('#site-search'); const query = input.value.trim(); if (!query) return input.focus(); state.search = query; state.filter = 'all'; document.querySelectorAll('.filter').forEach((filter) => filter.classList.toggle('active', filter.dataset.filter === 'all')); renderProducts(); closeSearch(); $('#shop')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); toast(`Showing results for “${query}”`); track('search', { search_term: query.slice(0, 80) }); }
function checkout() { if (!state.bag.length) return toast('Add a product before checkout'); const items = state.bag.map((item) => window.velouraAnalytics?.item(item, item.quantity) || { item_id: item.id, item_name: item.name, price: Number(item.price || 0), quantity: Number(item.quantity || 1) }); const value = items.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.quantity || 0), 0); track('begin_checkout', { currency: 'BDT', value, items }); window.location.href = new URL('./checkout.html', window.location.href).href; }
function bannerMatchesFilter(banner) { return !banner.categorySlug || state.filter === 'all' || state.filter === 'featured' || banner.categorySlug === state.filter; }
function bannerVisual(banner) { const image = String(banner.imageUrl || '').trim(); return /^(https:\/\/|\/assets\/|\/media\/)/i.test(image) ? `<img src="${escapeHtml(image)}" alt="" loading="lazy" />` : `<span class="marketing-banner-mark" aria-hidden="true">${icon('sparkle')}</span>`; }
function bannerContent(banner) { return `<span class="marketing-banner-copy"><small>${escapeHtml(banner.eyebrow || 'VELOURA EDIT')}</small><strong>${escapeHtml(banner.title || banner.body || 'A softer edit awaits')}</strong>${banner.body ? `<span>${escapeHtml(banner.body)}</span>` : ''}</span>`; }
function bannerCard(banner, extraClass = '') { const href = String(banner.linkUrl || '').trim(); const promotionAttrs = `data-promotion-id="${escapeHtml(String(banner.id || banner.title || 'veloura-promotion'))}" data-promotion-name="${escapeHtml(banner.title || 'Veloura promotion')}"`; const content = `${bannerVisual(banner)}${bannerContent(banner)}<span class="marketing-banner-arrow" aria-hidden="true">${icon('arrowUpRight')}</span>`; return href ? `<a class="marketing-banner-card ${extraClass}" ${promotionAttrs} href="${escapeHtml(href)}">${content}</a>` : `<div class="marketing-banner-card ${extraClass}" ${promotionAttrs}>${content}</div>`; }
function renderMarketingBanners(banners) { const root = $('#marketing-marquee-root'); if (!root) return; const marquee = (banners || []).filter((banner) => banner.placement === 'marquee' && bannerMatchesFilter(banner)); if (!marquee.length) { root.innerHTML = ''; return; } const speed = Math.min(90, Math.max(8, Number(marquee[0].marqueeSpeed || 22))); const trackMarkup = [...marquee, ...marquee].map((banner, index) => bannerCard(banner, index >= marquee.length ? 'is-duplicate' : '')).join(''); root.innerHTML = `<section class="marketing-marquee section-wrap" aria-label="Current Veloura offers"><div class="marketing-marquee-window"><div class="marketing-marquee-track" style="--marquee-duration:${speed}s">${trackMarkup}</div></div></section>`; marquee.forEach((banner) => track('view_promotion', { promotion_id: String(banner.id || banner.title || 'veloura-promotion'), promotion_name: banner.title || 'Veloura promotion', creative_slot: 'marquee' })); }
function closeOfferPopup() { const root = $('#offer-popup-root'); if (!root) return; const id = root.dataset.bannerId; if (id) { try { sessionStorage.setItem(`veloura-popup-dismissed-${id}`, '1'); } catch {} } root.classList.remove('open'); root.setAttribute('aria-hidden', 'true'); window.setTimeout(() => { root.innerHTML = ''; }, 220); }
function showOfferPopup(banners) { const root = $('#offer-popup-root'); if (!root) return; const popup = (banners || []).find((banner) => banner.placement === 'popup' && bannerMatchesFilter(banner)); if (!popup) return; try { if (sessionStorage.getItem(`veloura-popup-dismissed-${popup.id}`)) return; } catch {} root.dataset.bannerId = String(popup.id || ''); const href = String(popup.linkUrl || '').trim(); const body = `${bannerVisual(popup)}<div class="offer-popup-copy">${bannerContent(popup)}${href ? `<span class="offer-popup-cta">Explore the offer ${icon('arrowUpRight')}</span>` : ''}</div>`; root.innerHTML = `<div class="offer-popup-backdrop" data-close-offer></div><section class="offer-popup-card" role="dialog" aria-modal="true" aria-label="${escapeHtml(popup.title || 'Veloura offer')}">${href ? `<a class="offer-popup-link" data-promotion-id="${escapeHtml(String(popup.id || popup.title || 'veloura-popup'))}" data-promotion-name="${escapeHtml(popup.title || 'Veloura offer')}" href="${escapeHtml(href)}">${body}</a>` : body}<button class="offer-popup-close" type="button" data-close-offer aria-label="Close offer">${icon('close')}</button></section>`; root.classList.add('open'); root.setAttribute('aria-hidden', 'false'); track('view_promotion', { promotion_id: String(popup.id || popup.title || 'veloura-popup'), promotion_name: popup.title || 'Veloura offer', creative_slot: 'popup' }); root.querySelectorAll('[data-close-offer]').forEach((node) => node.addEventListener('click', closeOfferPopup)); }
function applyCmsContent(data) { const notice = data.content?.find((item) => item.key === 'topbar_notice'); try { const body = JSON.parse(notice?.body || '{}'); if (body.text) document.querySelector('.announcement').childNodes[0].textContent = `${body.text} · `; } catch {} const posts = data.posts || []; const cards = document.querySelectorAll('#journal .journal-grid article'); posts.slice(0, cards.length).forEach((post, index) => { const card = cards[index]; const title = card?.querySelector('h3'); const art = card?.querySelector('.journal-art'); const label = card?.querySelector('.eyebrow'); const image = String(post.coverImageUrl || post.imageUrl || '').trim(); if (title) title.innerHTML = `<a href="./blog.html?slug=${encodeURIComponent(post.slug)}">${escapeHtml(post.title)}</a>`; if (label) label.textContent = `${post.category || 'JOURNAL'}${post.subcategory ? ` · ${post.subcategory}` : ''}${post.duration ? ` · ${post.duration}` : ''}`; if (art && /^(https:\/\/|\/assets\/|\/media\/)/i.test(image)) { art.style.backgroundImage = `url("${image.replace(/"/g, '%22')}")`; art.classList.add('has-cms-image'); } }); state.marketingBanners = data.banners || []; renderMarketingBanners(state.marketingBanners); window.setTimeout(() => showOfferPopup(state.marketingBanners), 900); }
function mountChatWidget() { const widget = document.createElement('div'); widget.innerHTML = `<button id="chat-launcher" class="chat-launcher" aria-label="Open SmartGen support">${icon('sparkle')}<span class="sr-only">Open SmartGen support</span></button><section id="chat-panel" class="chat-panel" aria-hidden="true"><div class="chat-head"><div class="smartgen-brand"><span class="smartgen-mark">SG</span><div><a class="smartgen-title" href="https://smartgentools.com" target="_blank" rel="noopener">SmartGen</a><span class="smartgen-subtitle">Veloura beauty support</span></div></div><button id="chat-close" class="chat-close" aria-label="Close support">${icon('close')}</button></div><div class="chat-choice"><button class="chat-choice-button active" data-chat-mode="ai">Ask SmartGen</button><a class="chat-choice-button" href="https://wa.me/8801700000000" target="_blank" rel="noopener">WhatsApp</a></div><div id="chat-messages" class="chat-messages"><div class="chat-bubble assistant">হ্যালো! Product, price, usage, delivery বা order নিয়ে জানতে চাইলে লিখুন।</div></div><form id="chat-form" class="chat-form"><input id="chat-input" placeholder="আপনার প্রশ্ন লিখুন…" autocomplete="off" required /><button aria-label="Send message">${icon('arrowRight')}</button></form></section>`; document.body.appendChild(widget); $('#chat-launcher').addEventListener('click', () => { const panel = $('#chat-panel'); panel.classList.toggle('open'); panel.setAttribute('aria-hidden', String(!panel.classList.contains('open'))); }); $('#chat-close').addEventListener('click', () => { const panel = $('#chat-panel'); panel.classList.remove('open'); panel.setAttribute('aria-hidden', 'true'); }); $('#chat-form').addEventListener('submit', sendCustomerChat); }
function renderChatMessages() { const node = $('#chat-messages'); node.innerHTML = `<div class="chat-bubble assistant">হ্যালো! Product, price, usage, delivery বা order নিয়ে জানতে চাইলে লিখুন।</div>` + state.chatMessages.map((message) => { const cards = Array.isArray(message.products) ? `<div class="chat-product-list">${message.products.map((product) => { const href = new URL(`./product.html?slug=${encodeURIComponent(String(product.slug || ''))}${state.adminPreview ? '&admin_preview=1' : ''}`, window.location.href).href; const image = /^(https:\/\/|\/assets\/)/i.test(String(product.imageUrl || '')) ? product.imageUrl : './assets/asset-fallback.svg'; return `<a class="chat-product-card" href="${escapeHtml(href)}"><img src="${escapeHtml(image)}" alt="${escapeHtml(product.name)}" loading="lazy"><span class="chat-product-card-copy"><small>${escapeHtml(product.categoryName || 'Veloura edit')}</small><strong>${escapeHtml(product.name)}</strong><b>${money(product.price)}${Number(product.stock || 0) <= 0 ? ' <i>Stock out</i>' : ''}</b></span><span class="chat-product-arrow" aria-hidden="true">${icon('arrowUpRight')}</span></a>`; }).join('')}</div>` : ''; return `<div class="chat-bubble ${message.role}">${escapeHtml(message.content)}${cards}</div>`; }).join(''); node.scrollTop = node.scrollHeight; }
async function sendCustomerChat(event) { event.preventDefault(); const input = $('#chat-input'); const content = input.value.trim(); if (!content) return; input.value = ''; state.chatMessages.push({ role: 'user', content }); renderChatMessages(); input.disabled = true; try { const data = await api('/chat/customer', { method: 'POST', body: JSON.stringify({ visitorKey: state.visitorKey, messages: state.chatMessages }) }); state.chatMessages.push({ role: 'assistant', content: data.reply, products: data.products || [] }); renderChatMessages(); track('support_chat_message'); } catch { state.chatMessages.push({ role: 'assistant', content: 'দুঃখিত, এখন AI support পাওয়া যাচ্ছে না। WhatsApp-এ যোগাযোগ করুন: +880 1700-000000' }); renderChatMessages(); } finally { input.disabled = false; input.focus(); } }
const fallbackCategoryImages = { 'skin-care': '/manus-storage/veloura-lumen-serum_7770ea4d.png', 'face-care': './assets/asset-fallback.svg', 'hair-care': '/manus-storage/veloura-ritual-oil_5e40ea12.png', 'eyes-makeup': '/manus-storage/veloura-night-mist_60a09ac9.png', 'face-makeup': '/manus-storage/veloura-night-mist_60a09ac9.png', 'makeup': './assets/asset-fallback.svg', 'perfume': '/manus-storage/veloura-night-mist_60a09ac9.png' }; const fallbackCategories = ['Skin Care', 'Face Care', 'Face Makeup', 'Eyes Makeup', 'Makeup', 'Hair Care', 'Perfume', 'Kids'].map((name, index) => { const slug = name.toLowerCase().replaceAll(' ', '-'); return { name, slug, imageUrl: fallbackCategoryImages[slug] || (index % 3 === 0 ? '/manus-storage/veloura-lumen-serum_7770ea4d.png' : index % 3 === 1 ? './assets/asset-fallback.svg' : '/manus-storage/veloura-night-mist_60a09ac9.png') }; });
const fallbackProducts = [
  { id: 1, name: 'Lumen Dew Barrier Serum', slug: 'lumen-dew-barrier-serum', description: 'A lightweight daily serum for a calm, hydrated-looking ritual.', price: 890, compareAtPrice: 1090, imageUrl: '/manus-storage/veloura-lumen-serum_7770ea4d.png', stock: 24, rating: 0, reviewCount: 0, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 1 },
  { id: 2, name: 'Ritual Amber Body Oil', slug: 'ritual-amber-body-oil', description: 'A warm, nourishing body oil for slow evening rituals.', price: 760, compareAtPrice: 920, imageUrl: '/manus-storage/veloura-ritual-oil_5e40ea12.png', stock: 18, rating: 0, reviewCount: 0, categoryName: 'Body Care', categorySlug: 'body-care', featured: 1 },
  { id: 3, name: 'Cloud Veil Comfort Cream', slug: 'cloud-veil-comfort-cream', description: 'A soft daily cream with a plush, comfortable finish.', price: 690, compareAtPrice: 820, imageUrl: './assets/asset-fallback.svg', stock: 32, rating: 0, reviewCount: 0, categoryName: 'Face Care', categorySlug: 'face-care', featured: 1 },
  { id: 4, name: 'Afterglow Face Mist', slug: 'afterglow-face-mist', description: 'A refreshing mist to keep a simple routine feeling light.', price: 520, compareAtPrice: 640, imageUrl: '/manus-storage/veloura-night-mist_60a09ac9.png', stock: 26, rating: 0, reviewCount: 0, categoryName: 'Face Care', categorySlug: 'face-care', featured: 0 },
];
async function init() { mountChatWidget(); try { const [categories, products, content] = await Promise.all([api('/categories'), api('/products'), api('/content/home')]); renderCategories(categories.categories); state.products = products.products; renderProducts(); applyCmsContent(content); } catch (error) { renderCategories(fallbackCategories); state.products = fallbackProducts; renderProducts(); toast('Preview mode: showing curated Veloura products'); console.error(error); } renderBag(); }
document.addEventListener('click', (event) => { const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'menu') toggleMobileNav(true); if (action === 'close-menu') toggleMobileNav(false); if (event.target.id === 'mobile-nav-backdrop') toggleMobileNav(false); if (action === 'bag') toggleDrawer(true); if (action === 'close-bag') toggleDrawer(false); if (action === 'checkout') checkout(); if (action === 'search') openSearch(); if (action === 'close-search') closeSearch(); const suggestion = event.target.closest('[data-search-suggestion]')?.dataset.searchSuggestion; if (suggestion) { $('#site-search').value = suggestion; $('#search-form').requestSubmit(); } });
document.querySelectorAll('.mobile-nav a').forEach((link) => link.addEventListener('click', () => toggleMobileNav(false)));
document.querySelectorAll('.filter').forEach((button) => button.addEventListener('click', () => { state.filter = button.dataset.filter; document.querySelectorAll('.filter').forEach((filter) => filter.classList.toggle('active', filter === button)); renderProducts(); renderMarketingBanners(state.marketingBanners); track('product_filter', { filter: state.filter }); }));
$('#newsletter-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.target; const input = form.elements.namedItem('email'); const message = $('#newsletter-message'); const email = String(input?.value || '').trim(); if (!email) return; if (message) message.textContent = 'Joining…'; try { const data = await api('/newsletter', { method: 'POST', body: JSON.stringify({ email, source: 'footer' }) }); if (message) message.textContent = data.message || 'You are on the softer list.'; toast('You are on the softer list.'); form.reset(); track('newsletter_signup', { source: 'footer' }); } catch (error) { if (message) message.textContent = error.message || 'Could not save your email right now.'; } });

document.addEventListener('click', (event) => { if (event.target.closest('[data-close-offer]')) closeOfferPopup(); const promotion = event.target.closest('[data-promotion-id]'); if (promotion) track('select_promotion', { promotion_id: promotion.dataset.promotionId, promotion_name: promotion.dataset.promotionName, creative_slot: 'marquee' }); });
$('#search-form').addEventListener('submit', submitSearch);
$('#search-overlay').addEventListener('click', (event) => { if (event.target.classList.contains('search-overlay-backdrop')) closeSearch(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeSearch(); });
$('#bag-drawer').addEventListener('click', (event) => { if (event.target.id === 'bag-drawer') toggleDrawer(false); });
init();
