(() => {
  if (document.getElementById('chat-launcher')) return;
  const apiBase = window.VELOURA_API_BASE || '/api';
  const visitorKey = localStorage.getItem('veloura-visitor-key') || `visitor-${Math.random().toString(36).slice(2)}-${Date.now()}`;
  localStorage.setItem('veloura-visitor-key', visitorKey);
  const messages = [];
  const widget = document.createElement('div');
  widget.innerHTML = `<button id="chat-launcher" class="chat-launcher" aria-label="Open SmartGen support">SG<span class="sr-only">Open SmartGen support</span></button><section id="chat-panel" class="chat-panel" aria-hidden="true"><div class="chat-head"><div class="smartgen-brand"><span class="smartgen-mark">SG</span><div><a class="smartgen-title" href="https://smartgentools.com" target="_blank" rel="noopener">SmartGen</a><span class="smartgen-subtitle">Veloura beauty support</span></div></div><button id="chat-close" class="chat-close" aria-label="Close support">×</button></div><div class="chat-choice"><button class="chat-choice-button active" type="button">Ask SmartGen</button><a class="chat-choice-button" href="https://wa.me/8801700000000" target="_blank" rel="noopener">WhatsApp</a></div><div id="chat-messages" class="chat-messages"><div class="chat-bubble assistant">হ্যালো! Product, price, usage, delivery বা order নিয়ে জানতে চাইলে লিখুন।</div></div><form id="chat-form" class="chat-form"><input id="chat-input" placeholder="আপনার প্রশ্ন লিখুন…" autocomplete="off" required /><button aria-label="Send message">→</button></form></section>`;
  document.body.appendChild(widget);
  const panel = widget.querySelector('#chat-panel');
  const render = () => { widget.querySelector('#chat-messages').innerHTML = `<div class="chat-bubble assistant">হ্যালো! Product, price, usage, delivery বা order নিয়ে জানতে চাইলে লিখুন।</div>${messages.map((message) => `<div class="chat-bubble ${message.role}">${String(message.content).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}</div>`).join('')}`; };
  widget.querySelector('#chat-launcher').addEventListener('click', () => { panel.classList.toggle('open'); panel.setAttribute('aria-hidden', String(!panel.classList.contains('open'))); });
  widget.querySelector('#chat-close').addEventListener('click', () => { panel.classList.remove('open'); panel.setAttribute('aria-hidden', 'true'); });
  widget.querySelector('#chat-form').addEventListener('submit', async (event) => { event.preventDefault(); const input = widget.querySelector('#chat-input'); const content = input.value.trim(); if (!content || input.disabled) return; input.value = ''; messages.push({ role: 'user', content }); render(); input.disabled = true; try { const response = await fetch(`${apiBase}/chat/customer`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ visitorKey, messages }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Support unavailable'); messages.push({ role: 'assistant', content: data.reply || 'Please contact us on WhatsApp for help.' }); } catch { messages.push({ role: 'assistant', content: 'দুঃখিত, এখন AI support পাওয়া যাচ্ছে না। WhatsApp-এ যোগাযোগ করুন: +880 1700-000000' }); } finally { input.disabled = false; render(); input.focus(); } });
})();
