// Help: plain-language guides for the everyday jobs, plus the incident checklist.
import { t, tx } from "../i18n.js";
import { html } from "../core.js";

const GUIDES = [
  ["A buyer paid by bKash / Nagad and sent a TrxID", "Open Orders → “Payments to check”. Find that exact TrxID and amount in your merchant app or statement. Only then press “Confirm payment received”, type the TrxID and amount. The order is delivered at once (or held, if a safety rule applies). If the TrxID was already used on another order, the screen warns you.",
    "ক্রেতা বিকাশ / নগদে পেমেন্ট করে TrxID দিয়েছেন", "অর্ডার → “যাচাইয়ের পেমেন্ট” খুলুন। মার্চেন্ট অ্যাপ বা স্টেটমেন্টে ঠিক ওই TrxID ও টাকা খুঁজুন। তারপরই “পেমেন্ট পেয়েছি — নিশ্চিত করুন” চেপে TrxID ও টাকা লিখুন। অর্ডার সাথে সাথে ডেলিভারি হবে (নিরাপত্তা নিয়ম থাকলে আটকে থাকবে)। TrxID আগে অন্য অর্ডারে ব্যবহার হলে স্ক্রিনে সতর্কতা দেখাবে।"],
  ["Why is a paid order “held”?", "A safety rule matched: first order of a new buyer above the limit, a very large order, a buyer with chargebacks (🔴 Verify), or a device used with many phone numbers. Open the order, read the reasons, call the buyer if needed, then press Release — or Refund if it looks wrong.",
    "পেইড অর্ডার কেন “আটকে” আছে?", "একটি নিরাপত্তা নিয়ম মিলেছে: নতুন ক্রেতার সীমার বেশি প্রথম অর্ডার, খুব বড় অর্ডার, চার্জব্যাকসহ ক্রেতা (🔴 যাচাই করুন), বা অনেক ফোন নম্বরে ব্যবহৃত ডিভাইস। অর্ডার খুলে কারণ পড়ুন, দরকার হলে ক্রেতাকে কল করুন, তারপর রিলিজ — বা সন্দেহজনক হলে রিফান্ড।"],
  ["A seller missed the 30-minute deadline", "The line is escalated automatically and appears under “Late deliveries”. If the Official Store has the pack in stock, it's moved there by itself. Otherwise open the order and press Reassign to pick another seller, or “Deliver for seller” if your team tops it up.",
    "সেলার ৩০ মিনিটের সময়সীমা মিস করেছেন", "লাইনটি নিজে থেকে এসকেলেট হয়ে “দেরিতে ডেলিভারি” তে দেখায়। অফিসিয়াল স্টোরে স্টক থাকলে নিজেই সেখানে চলে যায়। নাহলে অর্ডার খুলে “অন্য সেলারকে দিন” চাপুন, বা আপনার টিম টপ-আপ দিলে “সেলারের হয়ে ডেলিভারি”।"],
  ["Reviewing a seller application", "Applications → open one. Check the ID photo, the selfie holding the same ID, that the phone is verified and the payout account name matches. Approve with a tier and deadline, ask for more info with a clear note, or reject. Viewing documents is logged.",
    "সেলার আবেদন যাচাই", "আবেদন → একটি খুলুন। পরিচয়পত্রের ছবি, একই পরিচয়পত্র হাতে সেলফি, ফোন যাচাই ও পেআউট অ্যাকাউন্টের নাম মিলছে কিনা দেখুন। টিয়ার ও সময়সীমা দিয়ে অনুমোদন, স্পষ্ট নোট দিয়ে আরও তথ্য চাওয়া, বা বাতিল। ডকুমেন্ট দেখা লগে থাকে।"],
  ["Resolving a dispute", "Read the buyer's report and the seller's answer. Code didn't work and the seller can't prove otherwise → Refund buyer. Delivery proven (top-up ref, screenshot) → Pay seller (doesn't count against them). Partly right → Split with an amount. The seller's money for that line was on hold meanwhile.",
    "বিরোধ সমাধান", "ক্রেতার রিপোর্ট ও সেলারের উত্তর পড়ুন। কোড কাজ করেনি আর সেলার প্রমাণ দিতে পারেননি → ক্রেতাকে রিফান্ড। ডেলিভারি প্রমাণিত (টপ-আপ রেফ, স্ক্রিনশট) → সেলারকে টাকা দিন (তাদের বিপক্ষে গণ্য হয় না)। আংশিক সঠিক → পরিমাণ দিয়ে ভাগাভাগি। এর মধ্যে ওই লাইনের সেলারের টাকা আটকে ছিল।"],
  ["Paying sellers", "Payouts → Requested. Approve, send the money from your bKash/Nagad/bank, then press “Mark paid” and type the transfer reference. Reject with a reason if something's off (the lines go back to the seller's balance).",
    "সেলারদের টাকা দেওয়া", "পেআউট → অনুরোধ। অনুমোদন দিন, বিকাশ/নগদ/ব্যাংক থেকে টাকা পাঠান, তারপর “পরিশোধিত” চেপে ট্রান্সফার রেফারেন্স লিখুন। গোলমাল মনে হলে কারণসহ বাতিল করুন (লাইনগুলো সেলারের ব্যালেন্সে ফিরে যাবে)।"],
  ["What do the badges mean?", "Buyers: 🟢 Trusted (3+ delivered, no chargebacks) · 🟡 New · 🔴 Verify (chargeback or blocked — every order held). Sellers: 🟢 Good standing · 🟡 Watch (complaints or late deliveries rising) · 🔴 Under review (many “not received” reports or a high complaint rate). Verified Seller is earned after 50 clean orders — it can't be granted by hand.",
    "ব্যাজগুলোর মানে কী?", "ক্রেতা: 🟢 বিশ্বস্ত (৩+ ডেলিভারি, চার্জব্যাক নেই) · 🟡 নতুন · 🔴 যাচাই করুন (চার্জব্যাক বা ব্লক — প্রতিটি অর্ডার আটকে থাকে)। সেলার: 🟢 ভালো অবস্থান · 🟡 নজরে (অভিযোগ বা দেরি বাড়ছে) · 🔴 পর্যালোচনায় (অনেক “পাইনি” রিপোর্ট বা উচ্চ অভিযোগের হার)। ভেরিফায়েড সেলার ৫০টি ঝামেলাহীন অর্ডারে অর্জিত — হাতে দেওয়া যায় না।"],
  ["Something looks wrong (incident checklist)", "1) Contain: suspend the seller or block the buyer; turn a payment method off in Settings if it's being abused. 2) Check the Audit log and Fraud & risk for what happened. 3) Refund affected buyers. 4) Rotate any leaked secret with wrangler secret put. 5) If data was changed, restore with D1 Time Travel (see docs/SECURITY.md). 6) Write down what happened and what you changed.",
    "কিছু ভুল মনে হচ্ছে (ঘটনা চেকলিস্ট)", "১) আটকান: সেলার স্থগিত বা ক্রেতা ব্লক করুন; অপব্যবহার হলে সেটিংসে পেমেন্ট পদ্ধতি বন্ধ করুন। ২) অডিট লগ ও প্রতারণা পেজে কী হয়েছে দেখুন। ৩) ক্ষতিগ্রস্ত ক্রেতাদের রিফান্ড দিন। ৪) কোনো সিক্রেট ফাঁস হলে wrangler secret put দিয়ে বদলান। ৫) ডেটা বদলে গেলে D1 Time Travel দিয়ে ফিরিয়ে আনুন (docs/SECURITY.md)। ৬) কী হয়েছে ও কী বদলেছেন লিখে রাখুন।"],
];

export default async function help(view) {
  view.innerHTML = String(html`<div class="page-head"><h1>${t("help")}</h1></div><div class="help">${GUIDES.map(([qe, ae, qb, ab]) => html`<details class="card" style="margin-bottom:10px"><summary><b>${tx(qe, qb)}</b></summary><p style="margin:10px 0 0">${tx(ae, ab)}</p></details>`)}</div>`);
}
