// Help center — short, plain-language guides for everyday tasks.
import { t, lang } from "../i18n.js";
import { html } from "../core.js";

const GUIDES = [
  { en: ["A new Cash on Delivery order came in — what do I do?", "Open Orders → 📞 Needs a call. Tap Call (or a WhatsApp button). After the call press one button: \"Customer confirmed\", \"No answer\" or \"Customer said no\". Confirmed orders get their invoice number (INV-JWL-…) and an SMS automatically. \"Customer said no\" cancels the order and puts the stock back."],
    bn: ["নতুন ক্যাশ অন ডেলিভারি অর্ডার এসেছে — কী করব?", "অর্ডার → 📞 কল করতে হবে খুলুন। কল (বা হোয়াটসঅ্যাপ) চাপুন। কলের পর একটি বাটন চাপুন: \"গ্রাহক কনফার্ম করেছেন\", \"ধরেননি\" বা \"গ্রাহক না বলেছেন\"। কনফার্ম হলে ইনভয়েস নম্বর (INV-JWL-…) ও SMS নিজে থেকেই যাবে। \"না বলেছেন\" চাপলে অর্ডার বাতিল হয়ে স্টক ফেরত যায়।"] },
  { en: ["What do 🟢 Trusted, 🟡 New and 🔴 Verify mean?", "🟢 Trusted: several past orders delivered, none refused — if their number was verified by SMS, the order is confirmed automatically. 🟡 New: first order or little history — call before shipping. 🔴 Verify before shipping: refused parcels before, poor courier history or a blocked number — always call, and consider asking for the delivery charge in advance. Tap the badge to see the reason."],
    bn: ["🟢 বিশ্বস্ত, 🟡 নতুন আর 🔴 যাচাই মানে কী?", "🟢 বিশ্বস্ত: আগে কয়েকটি অর্ডার ডেলিভারি হয়েছে, কোনোটি ফেরত নেই — SMS এ নম্বর যাচাই হলে অর্ডার নিজে থেকেই কনফার্ম হয়। 🟡 নতুন: প্রথম অর্ডার বা কম রেকর্ড — পাঠানোর আগে কল করুন। 🔴 পাঠানোর আগে যাচাই করুন: আগে পার্সেল নেননি, কুরিয়ার রেকর্ড খারাপ বা নম্বর ব্লকড — অবশ্যই কল করুন, প্রয়োজনে ডেলিভারি চার্জ আগে নিন। কারণ দেখতে ব্যাজে চাপুন।"] },
  { en: ["Why is the Confirm or Ship button greyed out?", "An order can only be confirmed when the phone was verified by SMS, the customer confirmed on a call, or it's prepaid. Anything that isn't 🟢 Trusted needs a logged \"Customer confirmed\" call before it can be shipped. Log the call and the button turns on."],
    bn: ["কনফার্ম বা শিপ বাটন ধূসর কেন?", "ফোন নম্বর SMS এ যাচাই হলে, কলে গ্রাহক কনফার্ম করলে বা আগে পেমেন্ট হলে তবেই অর্ডার কনফার্ম করা যায়। 🟢 বিশ্বস্ত না হলে পাঠানোর আগে \"গ্রাহক কনফার্ম করেছেন\" কল লিখে রাখতে হবে। কল লিখলেই বাটন চালু হবে।"] },
  { en: ["How do I send parcels?", "Pack the order and press → Packed. Then press → Shipped, choose Steadfast or Pathao and keep \"Book automatically\" ticked (if connected). Or type the tracking ID from the courier. To ship many at once, tick the orders and press \"Mark selected shipped\" — you'll be asked to confirm first."],
    bn: ["পার্সেল কীভাবে পাঠাব?", "অর্ডার প্যাক করে → প্যাকড চাপুন। তারপর → পাঠানো হয়েছে চাপুন, স্টেডফাস্ট বা পাঠাও বেছে \"অটোমেটিক বুক\" টিক রাখুন (যুক্ত থাকলে)। অথবা কুরিয়ারের ট্র্যাকিং আইডি লিখুন। একসাথে অনেকগুলো পাঠাতে অর্ডারে টিক দিয়ে \"নির্বাচিতগুলো শিপড করুন\" চাপুন — আগে নিশ্চিত করতে বলা হবে।"] },
  { en: ["The courier says the customer refused the parcel", "Open the order and press \"Refused at delivery\". Stock goes back, and it's counted separately from cancellations and returns so the customer's record stays accurate."],
    bn: ["কুরিয়ার বলছে গ্রাহক পার্সেল নেননি", "অর্ডার খুলে \"ডেলিভারিতে নেননি\" চাপুন। স্টক ফেরত যাবে এবং এটি বাতিল ও ফেরত থেকে আলাদা গোনা হয়, যাতে গ্রাহকের রেকর্ড ঠিক থাকে।"] },
  { en: ["A customer paid by bKash / Nagad and sent a TrxID", "The order appears under \"Mobile payments to check\" on the dashboard. Check the TrxID in your bKash/Nagad app. If the amount matches, open the order and press \"Mark as paid\"."],
    bn: ["গ্রাহক বিকাশ / নগদে টাকা পাঠিয়ে TrxID দিয়েছেন", "ড্যাশবোর্ডে \"মোবাইল পেমেন্ট যাচাই\" এ অর্ডারটি দেখাবে। আপনার বিকাশ/নগদ অ্যাপে TrxID মিলিয়ে দেখুন। টাকা মিললে অর্ডার খুলে \"পেমেন্ট পেয়েছি\" চাপুন।"] },
  { en: ["Someone started checkout but didn't order", "Abandoned checkouts shows everyone who typed a phone number and stopped. Tap Call or WhatsApp, or \"Send recovery message\" (it includes a link that restores their cart). Then mark Recovered or Not interested."],
    bn: ["কেউ চেকআউট শুরু করে অর্ডার করেননি", "অসম্পূর্ণ চেকআউটে যারা ফোন নম্বর দিয়ে থেমে গেছেন তাদের দেখা যায়। কল বা হোয়াটসঅ্যাপ চাপুন, অথবা \"রিকভারি মেসেজ পাঠান\" (কার্ট ফিরিয়ে আনার লিংকসহ)। তারপর \"অর্ডার হয়েছে\" বা \"আগ্রহী নন\" চাপুন।"] },
  { en: ["How do I add a new product?", "Products → Add new. Write the name in both languages, choose the category and occasions, type the weight in grams, add close-up photos on a plain dark background (the first is the cover), then one row per option (ring or bangle size, colour) with its finish and stock. Leave SKU blank — it's created automatically from category + finish (for example JWL-EAR-GLD-0088). Never call plated pieces “gold” or “silver”. Set status to Active to show it in the shop."],
    bn: ["নতুন পণ্য কীভাবে যোগ করব?", "পণ্য → নতুন যোগ করুন। দুই ভাষায় নাম, ক্যাটাগরি ও উপলক্ষ বেছে নিন, গ্রামে ওজন লিখুন, গাঢ় সাধারণ ব্যাকগ্রাউন্ডে কাছ থেকে তোলা ছবি দিন (প্রথমটি কভার), তারপর প্রতিটি অপশনের (আংটি/চুড়ির সাইজ, রং) জন্য একটি সারিতে ফিনিশ ও স্টক লিখুন। SKU খালি রাখুন — ক্যাটাগরি + ফিনিশ থেকে নিজে থেকেই তৈরি হবে (যেমন JWL-EAR-GLD-0088)। প্লেটেড গয়নাকে কখনো “সোনা” বা “রুপা” বলবেন না। দোকানে দেখাতে অবস্থা 'চালু' করুন।"] },
  { en: ["Can I show \"Nickel-free\" or \"Hypoallergenic\" badges?", "Only if you have a lab report for that piece. In the product form add the badge and attach the report (PDF or photo). The badge can't be saved or shown without its document — this protects you and customers with sensitive skin. The hallmark badge is only for genuine, BSTI-hallmarked gold or silver, which this shop doesn't sell."],
    bn: ["\"নিকেল-মুক্ত\" বা \"হাইপোঅ্যালার্জেনিক\" ব্যাজ দেখাতে পারি?", "শুধু ওই গয়নার ল্যাব রিপোর্ট থাকলে। পণ্যের ফর্মে ব্যাজ যোগ করে রিপোর্ট (PDF বা ছবি) যুক্ত করুন। ডকুমেন্ট ছাড়া ব্যাজ সংরক্ষণ বা দেখানো যায় না — এতে আপনি ও সংবেদনশীল ত্বকের ক্রেতা দুজনেই সুরক্ষিত। হলমার্ক ব্যাজ শুধু বিএসটিআই হলমার্ক করা আসল সোনা/রুপার জন্য, যা এই দোকানে বিক্রি হয় না।"] },
  { en: ["New stock arrived — and people were waiting", "Inventory → type the new total for each item, choose \"New stock arrived\" and press Save. If customers asked to be told, the dashboard shows \"Back in stock — people are waiting\": press \"Notify\" to message them."],
    bn: ["নতুন স্টক এসেছে — কেউ কেউ অপেক্ষায় ছিলেন", "ইনভেন্টরি → প্রতিটির নতুন মোট লিখে \"নতুন স্টক এসেছে\" বেছে সংরক্ষণ করুন। কেউ জানাতে বললে ড্যাশবোর্ডে \"স্টকে ফিরেছে — গ্রাহক অপেক্ষায়\" দেখাবে: \"জানান\" চাপুন।"] },
  { en: ["A customer wants to return something", "Returns & refunds shows requests from customers' accounts. Approve (or reject with a reason), press \"Item received\" when it arrives — the order becomes Returned and stock goes back — then \"Refund sent\" with the amount."],
    bn: ["গ্রাহক পণ্য ফেরত দিতে চান", "রিটার্ন ও রিফান্ডে গ্রাহকের অনুরোধ দেখা যায়। অনুমোদন করুন (বা কারণসহ বাতিল), পণ্য এলে \"পণ্য ফেরত পেয়েছি\" চাপুন — অর্ডার 'ফেরত' হবে, স্টক ফিরবে — তারপর টাকার পরিমাণসহ \"টাকা ফেরত দিয়েছি\"।"] },
  { en: ["How do I run a Facebook ad campaign?", "Campaign pages → Add new: pick one product, write a headline and offer. Share the link (/lp/your-page) in the ad. Orders from it are tagged with the ad's UTM, and Reports → Sales → Ad campaign shows revenue per campaign."],
    bn: ["ফেসবুক বিজ্ঞাপন ক্যাম্পেইন কীভাবে চালাব?", "ক্যাম্পেইন পেজ → নতুন যোগ করুন: একটি পণ্য, শিরোনাম ও অফার দিন। বিজ্ঞাপনে লিংকটি (/lp/your-page) দিন। সেখান থেকে আসা অর্ডারে বিজ্ঞাপনের UTM থাকবে, রিপোর্ট → বিক্রি → বিজ্ঞাপন ক্যাম্পেইনে প্রতিটির আয় দেখা যাবে।"] },
  { en: ["I deleted something by mistake", "Most things go to Trash first. Open the same page, tap Trash, and press Restore."],
    bn: ["ভুল করে কিছু মুছে ফেলেছি", "বেশিরভাগ জিনিস প্রথমে ট্র্যাশে যায়। একই পেজে ট্র্যাশ চাপুন, তারপর ফিরিয়ে আনুন চাপুন।"] },
  { en: ["Something looks wrong or a staff member left", "Staff & roles → turn off \"Can sign in\" for that person (they're signed out immediately). Check the Activity log to see who changed what. If payment or courier keys may be exposed, ask your developer to change them. A backup copy is made every night (Settings → Connected services & backups)."],
    bn: ["কিছু ভুল মনে হচ্ছে বা কোনো স্টাফ চলে গেছেন", "স্টাফ ও রোল → সেই ব্যক্তির \"সাইন ইন করতে পারবেন\" বন্ধ করুন (সাথে সাথে সাইন আউট হবেন)। কে কী বদলেছে তা কার্যক্রমের লগে দেখুন। পেমেন্ট বা কুরিয়ারের কী ফাঁস হতে পারে মনে হলে ডেভেলপারকে বদলাতে বলুন। প্রতি রাতে ব্যাকআপ কপি হয় (সেটিংস → সংযুক্ত সার্ভিস ও ব্যাকআপ)।"] },
];

export default function help(view) {
  view.innerHTML = String(html`<div class="page-head"><h1>${t("help")}</h1></div><p class="muted">${t("helpIntro")}</p>
    ${GUIDES.map((g) => { const [q, a] = g[lang()] ?? g.en; return html`<details class="card" style="padding:16px 20px"><summary style="font-weight:700;cursor:pointer;min-height:32px">${q}</summary><p style="margin:.6em 0 0">${a}</p></details>`; })}`);
}
