// Help center — short, plain-language guides for everyday tasks.
import { t, lang } from "../i18n.js";
import { html } from "../core.js";

const GUIDES = [
  { en: ["A new Cash on Delivery order came in — what do I do?", "Open Orders → 📞 Needs a call. Tap Call (or a WhatsApp button). After the call press one button: \"Customer confirmed\", \"No answer\" or \"Customer said no\". Confirmed orders get their invoice number (INV-GAD-…) and an SMS automatically. \"Customer said no\" cancels the order and puts the stock back."],
    bn: ["নতুন ক্যাশ অন ডেলিভারি অর্ডার এসেছে — কী করব?", "অর্ডার → 📞 কল করতে হবে খুলুন। কল (বা হোয়াটসঅ্যাপ) চাপুন। কলের পর একটি বাটন চাপুন: \"গ্রাহক কনফার্ম করেছেন\", \"ধরেননি\" বা \"গ্রাহক না বলেছেন\"। কনফার্ম হলে ইনভয়েস নম্বর (INV-GAD-…) ও SMS নিজে থেকেই যাবে। \"না বলেছেন\" চাপলে অর্ডার বাতিল হয়ে স্টক ফেরত যায়।"] },
  { en: ["What do 🟢 Trusted, 🟡 New and 🔴 Verify mean?", "🟢 Trusted: several past orders delivered, none refused — if their number was verified by SMS, the order is confirmed automatically. 🟡 New: first order or little history — call before shipping. 🔴 Verify before shipping: refused parcels before, poor courier history or a blocked number — always call, and consider asking for the delivery charge in advance. Tap the badge to see the reason."],
    bn: ["🟢 বিশ্বস্ত, 🟡 নতুন আর 🔴 যাচাই মানে কী?", "🟢 বিশ্বস্ত: আগে কয়েকটি অর্ডার ডেলিভারি হয়েছে, কোনোটি ফেরত নেই — SMS এ নম্বর যাচাই হলে অর্ডার নিজে থেকেই কনফার্ম হয়। 🟡 নতুন: প্রথম অর্ডার বা কম রেকর্ড — পাঠানোর আগে কল করুন। 🔴 পাঠানোর আগে যাচাই করুন: আগে পার্সেল নেননি, কুরিয়ার রেকর্ড খারাপ বা নম্বর ব্লকড — অবশ্যই কল করুন, প্রয়োজনে ডেলিভারি চার্জ আগে নিন। কারণ দেখতে ব্যাজে চাপুন।"] },
  { en: ["Why is the Confirm or Ship button greyed out?", "An order can only be confirmed when the phone was verified by SMS, the customer confirmed on a call, or it's prepaid. Anything that isn't 🟢 Trusted needs a logged \"Customer confirmed\" call before it can be shipped. Log the call and the button turns on."],
    bn: ["কনফার্ম বা শিপ বাটন ধূসর কেন?", "ফোন নম্বর SMS এ যাচাই হলে, কলে গ্রাহক কনফার্ম করলে বা আগে পেমেন্ট হলে তবেই অর্ডার কনফার্ম করা যায়। 🟢 বিশ্বস্ত না হলে পাঠানোর আগে \"গ্রাহক কনফার্ম করেছেন\" কল লিখে রাখতে হবে। কল লিখলেই বাটন চালু হবে।"] },
  { en: ["How do I send parcels?", "Pack the order and press → Packed. Then press → Shipped, choose Steadfast or Pathao and keep \"Book automatically\" ticked (if connected). Or type the tracking ID from the courier. To ship many at once, tick the orders and press \"Mark selected shipped\" — you'll be asked to confirm first."],
    bn: ["পার্সেল কীভাবে পাঠাব?", "অর্ডার প্যাক করে → প্যাকড চাপুন। তারপর → পাঠানো হয়েছে চাপুন, স্টেডফাস্ট বা পাঠাও বেছে \"অটোমেটিক বুক\" টিক রাখুন (যুক্ত থাকলে)। অথবা কুরিয়ারের ট্র্যাকিং আইডি লিখুন। একসাথে অনেকগুলো পাঠাতে অর্ডারে টিক দিয়ে \"নির্বাচিতগুলো শিপড করুন\" চাপুন — আগে নিশ্চিত করতে বলা হবে।"] },
  { en: ["The courier says the customer refused the parcel", "Open the order and press \"Refused at delivery\". Stock goes back, and it's counted separately from cancellations and returns so the customer's record stays accurate."],
    bn: ["কুরিয়ার বলছে গ্রাহক পার্সেল নেননি", "অর্ডার খুলে \"ডেলিভারিতে নেননি\" চাপুন। স্টক ফেরত যাবে এবং এটি বাতিল ও ফেরত থেকে আলাদা গোনা হয়, যাতে গ্রাহকের রেকর্ড ঠিক থাকে।"] },
  { en: ["A customer paid by bKash / Nagad and sent a TrxID", "The order appears under \"Mobile payments to check\" on the dashboard. Check the TrxID in your bKash/Nagad app. If the amount matches, open the order and press \"Mark as paid\"."],
    bn: ["গ্রাহক বিকাশ / নগদে টাকা পাঠিয়ে TrxID দিয়েছেন", "ড্যাশবোর্ডে \"মোবাইল পেমেন্ট যাচাই\" এ অর্ডারটি দেখাবে। আপনার বিকাশ/নগদ অ্যাপে TrxID মিলিয়ে দেখুন। টাকা মিললে অর্ডার খুলে \"পেমেন্ট পেয়েছি\" চাপুন।"] },
  { en: ["Someone started checkout but didn't order", "Abandoned checkouts shows everyone who typed a phone number and stopped. Tap Call or WhatsApp, or \"Send recovery message\" (it includes a link that restores their cart). Then mark Recovered or Not interested."],
    bn: ["কেউ চেকআউট শুরু করে অর্ডার করেননি", "অসম্পূর্ণ চেকআউটে যারা ফোন নম্বর দিয়ে থেমে গেছেন তাদের দেখা যায়। কল বা হোয়াটসঅ্যাপ চাপুন, অথবা \"রিকভারি মেসেজ পাঠান\" (কার্ট ফিরিয়ে আনার লিংকসহ)। তারপর \"অর্ডার হয়েছে\" বা \"আগ্রহী নন\" চাপুন।"] },
  { en: ["How do I add a new product?", "Products → Add new. Write the name in both languages, pick the category and brand, and tick every device it works with (iPhone, Android, USB-C, laptop …) — that drives the \"Works with\" filter and the gadget finder. Fill the spec sheet one line at a time: pick a standard name (Battery, Bluetooth, Water resistance …) so it lines up in the comparison table, and copy the values exactly as printed on the box. Add up to 4 key features, what's in the box, and the warranty in months (0 = none). Under \"Sizes, colours & stock\" add one row per option and colour — leave SKU empty and it's created for you (GAD-EB-SON-BLK-0007). A product can't go live without a spec sheet."],
    bn: ["নতুন পণ্য কীভাবে যোগ করব?", "পণ্য → নতুন যোগ করুন। দুই ভাষায় নাম, ক্যাটাগরি ও ব্র্যান্ড দিন, আর যে যে ডিভাইসে চলে সব টিক দিন (আইফোন, অ্যান্ড্রয়েড, USB-C, ল্যাপটপ …) — এতে \"সাপোর্ট করে\" ফিল্টার ও গ্যাজেট ফাইন্ডার কাজ করে। স্পেক শিট এক লাইন করে দিন: আদর্শ নাম বেছে নিন (ব্যাটারি, ব্লুটুথ, পানি প্রতিরোধ …) যাতে তুলনা টেবিলে মিলে যায়, আর বক্সে যেভাবে লেখা হুবহু মান দিন। সর্বোচ্চ ৪টি মূল ফিচার, বক্সে যা আছে, আর ওয়ারেন্টি কত মাস (০ = নেই) দিন। \"সাইজ, রং ও স্টক\" এ প্রতিটি অপশন ও রঙের জন্য একটি সারি — SKU খালি রাখলে নিজে তৈরি হবে (GAD-EB-SON-BLK-0007)। স্পেক শিট ছাড়া পণ্য চালু করা যায় না।"] },
  { en: ["How do I run a Deal of the Day?", "Open the product, set a discount (or a sale price), then pick the date in \"Deal of the Day ends on\". The home page counts down to midnight Bangladesh time on that day, the badge shows the real stock left, and the sale price ends by itself that night — there's no fake timer that resets. Leave the date empty for an ordinary sale."],
    bn: ["আজকের ডিল কীভাবে চালাব?", "পণ্য খুলে ছাড় (বা ছাড়ের দাম) দিন, তারপর \"আজকের ডিল শেষ হবে\" এ তারিখ বেছে নিন। হোমপেজে সেই দিনের বাংলাদেশ সময় রাত ১২টা পর্যন্ত কাউন্টডাউন দেখাবে, ব্যাজে আসল স্টক দেখাবে, আর সেই রাতে ছাড়ের দাম নিজে থেকে শেষ হবে — বারবার রিসেট হওয়া ভুয়া টাইমার নেই। সাধারণ ছাড়ের জন্য তারিখ খালি রাখুন।"] },
  { en: ["Can I show \"Official warranty\", \"BTRC approved\" or \"Authorised\" badges?", "Only with proof. Trust badges lists the kinds of badge (with their icon). If one document covers a whole brand (e.g. your distribution letter), attach it there. If it's for one product (e.g. its BTRC approval), tick the badge in that product's form and attach the document. A badge without proof is saved but never shown, and expired documents stop showing automatically."],
    bn: ["\"অফিশিয়াল ওয়ারেন্টি\", \"বিটিআরসি অনুমোদিত\" বা \"অনুমোদিত পরিবেশক\" ব্যাজ দেখাতে পারি?", "শুধু প্রমাণ থাকলে। 'ট্রাস্ট ব্যাজ' মেনুতে ব্যাজের ধরন (আইকনসহ) থাকে। একটি ডকুমেন্ট পুরো ব্র্যান্ডের জন্য হলে (যেমন পরিবেশক চিঠি) সেখানে যুক্ত করুন। একটি পণ্যের জন্য হলে (যেমন বিটিআরসি অনুমোদন) সেই পণ্যের ফর্মে ব্যাজ টিক দিয়ে ডকুমেন্ট দিন। প্রমাণ ছাড়া ব্যাজ সংরক্ষিত হয় কিন্তু দেখায় না, আর মেয়াদ শেষ হলে নিজে থেকেই সরে যায়।"] },
  { en: ["New stock arrived — how do I add it?", "Inventory → Stock lots → Receive stock. Pick the option (SKU), type the supplier's invoice or lot number, the quantity and the cost price. Leave the expiry empty unless the item is dated (e.g. batteries). For high-value items paste the serial numbers too, one per line — they're picked when the order is packed, printed on the invoice and checked when a warranty claim comes in."],
    bn: ["নতুন স্টক এসেছে — কীভাবে যোগ করব?", "ইনভেন্টরি → স্টক লট → স্টক গ্রহণ। অপশন (SKU) বেছে সাপ্লায়ারের ইনভয়েস বা লট নম্বর, পরিমাণ ও কেনা দাম দিন। পণ্যে তারিখ না থাকলে (যেমন ব্যাটারি ছাড়া) মেয়াদ খালি রাখুন। দামি পণ্যের সিরিয়াল নম্বরও দিন, প্রতি লাইনে একটি — অর্ডার প্যাকের সময় এগুলো বেছে নেওয়া হয়, ইনভয়েসে ছাপা হয় এবং ওয়ারেন্টি ক্লেইমে মিলিয়ে দেখা হয়।"] },
  { en: ["A customer opened a warranty claim", "Warranty claims shows each claim with its order line, the warranty end date and the serial numbers we sent. Move it Submitted → Under review → Approved or Rejected (give the customer a reason) → Resolved (repaired, replaced or refunded, with a note). The customer gets an SMS at each step. A replace or refund marks the old serial as faulty so it can't be sold again."],
    bn: ["গ্রাহক ওয়ারেন্টি ক্লেইম করেছেন", "ওয়ারেন্টি ক্লেইমে প্রতিটি ক্লেইম তার অর্ডার লাইন, ওয়ারেন্টি শেষের তারিখ আর আমরা যে সিরিয়াল পাঠিয়েছি তা সহ দেখায়। ধাপে ধাপে এগিয়ে নিন: জমা হয়েছে → যাচাই চলছে → অনুমোদিত বা বাতিল (গ্রাহককে কারণ দিন) → সমাধান (মেরামত, বদল বা টাকা ফেরত, নোটসহ)। প্রতিটি ধাপে গ্রাহক SMS পাবেন। বদল বা টাকা ফেরত হলে পুরোনো সিরিয়াল ত্রুটিপূর্ণ হিসেবে চিহ্নিত হয়, যাতে আবার বিক্রি না হয়।"] },
  { en: ["A customer wants to return something", "Returns & refunds shows requests from customers' accounts. Approve (or reject with a reason), press \"Item received\" when it arrives — the order becomes Returned — then \"Refund sent\" with the amount. Check the box and seals: an unopened item can go back on sale, an opened or faulty one should be written off in Inventory → Stock lots (or handled as a warranty claim)."],
    bn: ["গ্রাহক পণ্য ফেরত দিতে চান", "রিটার্ন ও রিফান্ডে গ্রাহকের অনুরোধ দেখা যায়। অনুমোদন করুন (বা কারণসহ বাতিল), পণ্য এলে \"পণ্য ফেরত পেয়েছি\" চাপুন — অর্ডার 'ফেরত' হবে — তারপর পরিমাণসহ \"টাকা ফেরত দিয়েছি\"। বক্স ও সিল দেখুন: না খোলা পণ্য আবার বিক্রি করা যায়, খোলা বা ত্রুটিপূর্ণ হলে ইনভেন্টরি → স্টক লটে রাইট-অফ করুন (বা ওয়ারেন্টি ক্লেইম হিসেবে দেখুন)।"] },
  { en: ["How do I make a combo bundle?", "A bundle is its own product — e.g. \"iPhone travel kit\" — with its own SKU, price, stock and photo. Create it under Products, then in \"Bundle contents\" pick the products packed inside (at least 2). The shop lists what's inside, links to each product and shows the real saving against buying them separately (the build refuses a bundle that doesn't save money)."],
    bn: ["কম্বো বান্ডেল কীভাবে বানাব?", "বান্ডেল নিজেই একটি পণ্য — যেমন \"আইফোন ট্রাভেল কিট\" — যার নিজস্ব SKU, দাম, স্টক ও ছবি আছে। পণ্য মেনুতে তৈরি করে \"বান্ডেলে যা আছে\" অংশে ভেতরের পণ্যগুলো বেছে নিন (অন্তত ২টি)। দোকানে ভেতরে কী আছে, প্রতিটির লিংক আর আলাদা কেনার চেয়ে আসল সাশ্রয় দেখায়।"] },
  { en: ["Customers asked questions on a product page", "Product Q&A lists new questions. Type an answer and press Publish — it shows on the product page. Hide spam or anything you can't answer honestly. Answer from the spec sheet; if you don't know, say so and check with the supplier."],
    bn: ["গ্রাহক পণ্যের পেজে প্রশ্ন করেছেন", "পণ্যের প্রশ্নোত্তরে নতুন প্রশ্ন দেখা যায়। উত্তর লিখে প্রকাশ চাপুন — পণ্যের পেজে দেখাবে। স্প্যাম বা যা সৎভাবে উত্তর দিতে পারবেন না তা লুকিয়ে রাখুন। স্পেক শিট দেখে উত্তর দিন; না জানলে তা বলুন এবং সাপ্লায়ারের কাছে জেনে নিন।"] },
  { en: ["Why was my product description refused?", "Copy must match the spec sheet. Phrases like \"100% waterproof\" (give the IP rating instead), \"unbreakable\", \"lifetime warranty\", \"best in Bangladesh\", fake stock counts (\"only 2 left!\"), \"selling fast\" or \"offer ends today\" are refused in English and Bangla, and the message shows the exact phrase with a suggested rewrite. Real stock and real deal end dates are shown by the shop itself."],
    bn: ["পণ্যের বিবরণ কেন সংরক্ষণ হলো না?", "লেখা স্পেক শিটের সাথে মিলতে হবে। \"১০০% ওয়াটারপ্রুফ\" (এর বদলে IP রেটিং দিন), \"ভাঙবে না\", \"আজীবন ওয়ারেন্টি\", \"বাংলাদেশের সেরা\", বানানো স্টক (\"মাত্র ২টি বাকি!\"), \"দ্রুত বিক্রি হচ্ছে\" বা \"আজই অফার শেষ\" ইংরেজি ও বাংলায় গ্রহণ করা হয় না, আর মেসেজে ঠিক কোন শব্দ তা ও বিকল্প লেখা দেখায়। আসল স্টক ও ডিলের আসল শেষ তারিখ দোকান নিজেই দেখায়।"] },
  { en: ["How do I run a Facebook ad campaign?", "Campaign pages → Add new: pick one product, write a headline and offer. Share the link (/lp/your-page) in the ad. Orders from it are tagged with the ad's UTM, and Reports → Sales → Ad campaign shows revenue per campaign."],
    bn: ["ফেসবুক বিজ্ঞাপন ক্যাম্পেইন কীভাবে চালাব?", "ক্যাম্পেইন পেজ → নতুন যোগ করুন: একটি পণ্য, শিরোনাম ও অফার দিন। বিজ্ঞাপনে লিংকটি (/lp/your-page) দিন। সেখান থেকে আসা অর্ডারে বিজ্ঞাপনের UTM থাকবে, রিপোর্ট → বিক্রি → বিজ্ঞাপন ক্যাম্পেইনে প্রতিটির আয় দেখা যাবে।"] },
  { en: ["I deleted something by mistake", "Most things go to Trash first. Open the same page, tap Trash, and press Restore."],
    bn: ["ভুল করে কিছু মুছে ফেলেছি", "বেশিরভাগ জিনিস প্রথমে ট্র্যাশে যায়। একই পেজে ট্র্যাশ চাপুন, তারপর ফিরিয়ে আনুন চাপুন।"] },
  { en: ["Something looks wrong or a staff member left", "Staff & roles → turn off \"Can sign in\" for that person (they're signed out immediately). Check the Activity log to see who changed what. If payment or courier keys may be exposed, ask your developer to change them. A backup copy is made every night (Settings → Connected services & backups)."],
    bn: ["কিছু ভুল মনে হচ্ছে বা কোনো স্টাফ চলে গেছেন", "স্টাফ ও রোল → সেই ব্যক্তির \"সাইন ইন করতে পারবেন\" বন্ধ করুন (সাথে সাথে সাইন আউট হবেন)। কে কী বদলেছে তা কার্যক্রমের লগে দেখুন। পেমেন্ট বা কুরিয়ারের কী ফাঁস হতে পারে মনে হলে ডেভেলপারকে বদলাতে বলুন। প্রতি রাতে ব্যাকআপ কপি হয় (সেটিংস → সংযুক্ত সার্ভিস ও ব্যাকআপ)।"] },
];

export default function help(view) {
  view.innerHTML = String(html`<div class="page-head"><h1>${t("help")}</h1></div><p class="muted">${t("helpIntro")}</p>
    ${GUIDES.map((g) => { const [q, a] = g[lang()] ?? g.en; return html`<details class="card" style="padding:16px 20px"><summary style="font-weight:700;cursor:pointer;min-height:32px">${q}</summary><p style="margin:.6em 0 0">${a}</p></details>`; })}`);
}
