// Help center — short, plain-language guides for everyday tasks.
import { t, lang } from "../i18n.js";
import { html } from "../core.js";

const GUIDES = [
  { en: ["A new Cash on Delivery order came in — what do I do?", "Open Orders → 📞 Needs a call. Tap Call (or a WhatsApp button). After the call press one button: \"Customer confirmed\", \"No answer\" or \"Customer said no\". Confirmed orders get their invoice number (INV-SKN-…) and an SMS automatically. \"Customer said no\" cancels the order and puts the stock back."],
    bn: ["নতুন ক্যাশ অন ডেলিভারি অর্ডার এসেছে — কী করব?", "অর্ডার → 📞 কল করতে হবে খুলুন। কল (বা হোয়াটসঅ্যাপ) চাপুন। কলের পর একটি বাটন চাপুন: \"গ্রাহক কনফার্ম করেছেন\", \"ধরেননি\" বা \"গ্রাহক না বলেছেন\"। কনফার্ম হলে ইনভয়েস নম্বর (INV-SKN-…) ও SMS নিজে থেকেই যাবে। \"না বলেছেন\" চাপলে অর্ডার বাতিল হয়ে স্টক ফেরত যায়।"] },
  { en: ["What do 🟢 Trusted, 🟡 New and 🔴 Verify mean?", "🟢 Trusted: several past orders delivered, none refused — if their number was verified by SMS, the order is confirmed automatically. 🟡 New: first order or little history — call before shipping. 🔴 Verify before shipping: refused parcels before, poor courier history or a blocked number — always call, and consider asking for the delivery charge in advance. Tap the badge to see the reason."],
    bn: ["🟢 বিশ্বস্ত, 🟡 নতুন আর 🔴 যাচাই মানে কী?", "🟢 বিশ্বস্ত: আগে কয়েকটি অর্ডার ডেলিভারি হয়েছে, কোনোটি ফেরত নেই — SMS এ নম্বর যাচাই হলে অর্ডার নিজে থেকেই কনফার্ম হয়। 🟡 নতুন: প্রথম অর্ডার বা কম রেকর্ড — পাঠানোর আগে কল করুন। 🔴 পাঠানোর আগে যাচাই করুন: আগে পার্সেল নেননি, কুরিয়ার রেকর্ড খারাপ বা নম্বর ব্লকড — অবশ্যই কল করুন, প্রয়োজনে ডেলিভারি চার্জ আগে নিন। কারণ দেখতে ব্যাজে চাপুন।"] },
  { en: ["Why is the Confirm or Ship button greyed out?", "An order can only be confirmed when the phone was verified by SMS, the customer confirmed on a call, or it's prepaid. Anything that isn't 🟢 Trusted needs a logged \"Customer confirmed\" call before it can be shipped. Log the call and the button turns on."],
    bn: ["কনফার্ম বা শিপ বাটন ধূসর কেন?", "ফোন নম্বর SMS এ যাচাই হলে, কলে গ্রাহক কনফার্ম করলে বা আগে পেমেন্ট হলে তবেই অর্ডার কনফার্ম করা যায়। 🟢 বিশ্বস্ত না হলে পাঠানোর আগে \"গ্রাহক কনফার্ম করেছেন\" কল লিখে রাখতে হবে। কল লিখলেই বাটন চালু হবে।"] },
  { en: ["How do I send parcels?", "Pack the order and press → Packed. Then press → Shipped, choose Steadfast or Pathao and keep \"Book automatically\" ticked (if connected). Or type the tracking ID from the courier. To ship many at once, tick the orders and press \"Mark selected shipped\" — you'll be asked to confirm first."],
    bn: ["পার্সেল কীভাবে পাঠাব?", "অর্ডার প্যাক করে → প্যাকড চাপুন। তারপর → পাঠানো হয়েছে চাপুন, স্টেডফাস্ট বা পাঠাও বেছে \"অটোমেটিক বুক\" টিক রাখুন (যুক্ত থাকলে)। অথবা কুরিয়ারের ট্র্যাকিং আইডি লিখুন। একসাথে অনেকগুলো পাঠাতে অর্ডারে টিক দিয়ে \"নির্বাচিতগুলো শিপড করুন\" চাপুন — আগে নিশ্চিত করতে বলা হবে।"] },
  { en: ["The courier says the customer refused the parcel", "Open the order and press \"Refused at delivery\". Stock goes back, and it's counted separately from cancellations and returns so the customer's record stays accurate."],
    bn: ["কুরিয়ার বলছে গ্রাহক পার্সেল নেননি", "অর্ডার খুলে \"ডেলিভারিতে নেননি\" চাপুন। স্টক ফেরত যাবে এবং এটি বাতিল ও ফেরত থেকে আলাদা গোনা হয়, যাতে গ্রাহকের রেকর্ড ঠিক থাকে।"] },
  { en: ["A customer paid by bKash / Nagad and sent a TrxID", "The order appears under \"Mobile payments to check\" on the dashboard. Check the TrxID in your bKash/Nagad app. If the amount matches, open the order and press \"Mark as paid\"."],
    bn: ["গ্রাহক বিকাশ / নগদে টাকা পাঠিয়ে TrxID দিয়েছেন", "ড্যাশবোর্ডে \"মোবাইল পেমেন্ট যাচাই\" এ অর্ডারটি দেখাবে। আপনার বিকাশ/নগদ অ্যাপে TrxID মিলিয়ে দেখুন। টাকা মিললে অর্ডার খুলে \"পেমেন্ট পেয়েছি\" চাপুন।"] },
  { en: ["Someone started checkout but didn't order", "Abandoned checkouts shows everyone who typed a phone number and stopped. Tap Call or WhatsApp, or \"Send recovery message\" (it includes a link that restores their cart). Then mark Recovered or Not interested."],
    bn: ["কেউ চেকআউট শুরু করে অর্ডার করেননি", "অসম্পূর্ণ চেকআউটে যারা ফোন নম্বর দিয়ে থেমে গেছেন তাদের দেখা যায়। কল বা হোয়াটসঅ্যাপ চাপুন, অথবা \"রিকভারি মেসেজ পাঠান\" (কার্ট ফিরিয়ে আনার লিংকসহ)। তারপর \"অর্ডার হয়েছে\" বা \"আগ্রহী নন\" চাপুন।"] },
  { en: ["How do I add a new product?", "Products → Add new. Write the name in both languages, choose the category, the skin types it suits and the concerns it helps with. Paste the full ingredient list (INCI) exactly as printed on the pack, add 2–3 hero ingredients with one cosmetic line each, the steps for how to use it and any cautions. Add clear photos (the first is the cover), then one row per size (for example 30 ml or 50 g) with its price and stock. Leave SKU blank — it's created from category + size (for example SKN-SRM-30ML-0001). Use cosmetic wording only: never \"cures\", \"treats acne\" or \"heals\" — the form will stop you. Set status to Active to show it in the shop."],
    bn: ["নতুন পণ্য কীভাবে যোগ করব?", "পণ্য → নতুন যোগ করুন। দুই ভাষায় নাম, ক্যাটাগরি, কোন ত্বকের জন্য ও কোন সমস্যায় কাজে লাগে বেছে নিন। প্যাকেটে যেভাবে লেখা সেভাবে সম্পূর্ণ উপাদান তালিকা (INCI) দিন, ২–৩টি মূল উপাদান একটি করে কসমেটিক বাক্যসহ, ব্যবহারের ধাপ ও সতর্কতা লিখুন। পরিষ্কার ছবি দিন (প্রথমটি কভার), তারপর প্রতিটি সাইজের (যেমন ৩০ মিলি বা ৫০ গ্রাম) জন্য একটি সারিতে দাম ও স্টক। SKU খালি রাখুন — ক্যাটাগরি + সাইজ থেকে নিজে থেকেই তৈরি হবে (যেমন SKN-SRM-30ML-0001)। শুধু কসমেটিক শব্দ ব্যবহার করুন: কখনো \"সারায়\", \"ব্রণ দূর করে\" বা \"নিরাময়\" নয় — ফর্মই আটকে দেবে। দোকানে দেখাতে অবস্থা 'চালু' করুন।"] },
  { en: ["Can I show \"Dermatologically tested\", \"Halal\" or \"BSTI\" badges?", "Only with proof. In the product form add the badge and attach the certificate or test report (PDF or photo). A badge can't be saved or shown without its document — this protects you and your customers. Badges like \"Fragrance-free\" or \"Vegan\" must match the ingredient list."],
    bn: ["\"ডার্মাটোলজিক্যালি টেস্টেড\", \"হালাল\" বা \"বিএসটিআই\" ব্যাজ দেখাতে পারি?", "শুধু প্রমাণ থাকলে। পণ্যের ফর্মে ব্যাজ যোগ করে সার্টিফিকেট বা টেস্ট রিপোর্ট (PDF বা ছবি) যুক্ত করুন। ডকুমেন্ট ছাড়া ব্যাজ সংরক্ষণ বা দেখানো যায় না — এতে আপনি ও গ্রাহক দুজনেই সুরক্ষিত। \"সুগন্ধিমুক্ত\" বা \"ভেগান\" ব্যাজ উপাদান তালিকার সাথে মিলতে হবে।"] },
  { en: ["New stock arrived — how do I add it with the expiry date?", "Inventory → Batches & expiry → Receive stock. Pick the product size, type the batch / lot number and expiry date exactly as printed on the box, and the quantity. Orders are always packed from the batch that expires first, and the order page shows which batch to pick. Expired units are taken off sale automatically every night. If customers asked to be told, the dashboard shows \"Back in stock — people are waiting\": press \"Notify\"."],
    bn: ["নতুন স্টক এসেছে — মেয়াদসহ কীভাবে যোগ করব?", "ইনভেন্টরি → ব্যাচ ও মেয়াদ → স্টক গ্রহণ। পণ্যের সাইজ বেছে বাক্সে যেভাবে লেখা সেভাবে ব্যাচ / লট নম্বর, মেয়াদ শেষের তারিখ ও পরিমাণ লিখুন। অর্ডার সবসময় যে ব্যাচের মেয়াদ আগে শেষ হবে সেখান থেকে প্যাক হয়, আর অর্ডার পেজে কোন ব্যাচ থেকে নেবেন তা লেখা থাকে। মেয়াদোত্তীর্ণ পণ্য প্রতি রাতে নিজে থেকেই বিক্রি থেকে সরে যায়। কেউ জানাতে বললে ড্যাশবোর্ডে \"স্টকে ফিরেছে — গ্রাহক অপেক্ষায়\" দেখাবে: \"জানান\" চাপুন।"] },
  { en: ["A customer wants to return something", "Returns & refunds shows requests from customers' accounts. Approve (or reject with a reason), press \"Item received\" when it arrives — the order becomes Returned — then \"Refund sent\" with the amount. For hygiene, returned skincare is not put back on sale: write it off in Inventory → Batches. If the customer says their skin didn't agree with a product, be kind, refund if your policy allows, and suggest they speak to a dermatologist if irritation continues."],
    bn: ["গ্রাহক পণ্য ফেরত দিতে চান", "রিটার্ন ও রিফান্ডে গ্রাহকের অনুরোধ দেখা যায়। অনুমোদন করুন (বা কারণসহ বাতিল), পণ্য এলে \"পণ্য ফেরত পেয়েছি\" চাপুন — অর্ডার 'ফেরত' হবে — তারপর টাকার পরিমাণসহ \"টাকা ফেরত দিয়েছি\"। স্বাস্থ্যবিধির কারণে ফেরত আসা স্কিনকেয়ার আর বিক্রি হয় না: ইনভেন্টরি → ব্যাচ থেকে বাদ দিন। গ্রাহকের ত্বকে না মানালে সহানুভূতির সাথে কথা বলুন, নীতি অনুযায়ী টাকা ফেরত দিন এবং জ্বালা থাকলে চর্মরোগ বিশেষজ্ঞের পরামর্শ নিতে বলুন।"] },
  { en: ["A studio booking request came in", "Bookings shows requests by day. Call or WhatsApp the customer, then press \"Confirm booking\" — they get an SMS with the date, time and studio address. Need another time? Press \"Change time\" (the slot must be free). After the visit press \"Mark done\", or \"No-show\" if they didn't come. Opening hours, closed days and how many clients you can see at once are in Settings → Studio hours & bookings."],
    bn: ["স্টুডিও বুকিংয়ের অনুরোধ এসেছে", "বুকিং পেজে দিন অনুযায়ী অনুরোধ দেখা যায়। গ্রাহককে কল বা হোয়াটসঅ্যাপ করে \"বুকিং কনফার্ম\" চাপুন — তারিখ, সময় ও স্টুডিওর ঠিকানাসহ SMS যাবে। অন্য সময় লাগলে \"সময় বদলান\" চাপুন (স্লট খালি থাকতে হবে)। ভিজিটের পর \"সম্পন্ন\", না এলে \"আসেননি\" চাপুন। খোলার সময়, বন্ধের দিন ও একসাথে কতজন — সেটিংস → স্টুডিওর সময় ও বুকিং।"] },
  { en: ["What does the skin quiz recommend?", "The quiz asks skin type, main concern, budget and morning or night. It builds a simple routine (cleanse → treat → moisturise → protect) from active products with stock that suit that skin type. Mark your best products as Featured so they're picked first when two match equally."],
    bn: ["স্কিন কুইজ কী সাজেস্ট করে?", "কুইজ ত্বকের ধরন, প্রধান সমস্যা, বাজেট আর সকাল না রাত জানতে চায়। তারপর স্টকে থাকা চালু পণ্য থেকে ওই ত্বকের জন্য সহজ রুটিন (ক্লেনজ → ট্রিট → ময়েশ্চারাইজ → প্রোটেক্ট) বানায়। সমান মিললে যেন আপনার সেরা পণ্য আগে আসে, সেজন্য সেগুলো ফিচার্ড করুন।"] },
  { en: ["How do I run a Facebook ad campaign?", "Campaign pages → Add new: pick one product, write a headline and offer. Share the link (/lp/your-page) in the ad. Orders from it are tagged with the ad's UTM, and Reports → Sales → Ad campaign shows revenue per campaign."],
    bn: ["ফেসবুক বিজ্ঞাপন ক্যাম্পেইন কীভাবে চালাব?", "ক্যাম্পেইন পেজ → নতুন যোগ করুন: একটি পণ্য, শিরোনাম ও অফার দিন। বিজ্ঞাপনে লিংকটি (/lp/your-page) দিন। সেখান থেকে আসা অর্ডারে বিজ্ঞাপনের UTM থাকবে, রিপোর্ট → বিক্রি → বিজ্ঞাপন ক্যাম্পেইনে প্রতিটির আয় দেখা যাবে।"] },
  { en: ["I deleted something by mistake", "Most things go to Trash first. Open the same page, tap Trash, and press Restore."],
    bn: ["ভুল করে কিছু মুছে ফেলেছি", "বেশিরভাগ জিনিস প্রথমে ট্র্যাশে যায়। একই পেজে ট্র্যাশ চাপুন, তারপর ফিরিয়ে আনুন চাপুন।"] },
  { en: ["Something looks wrong or a staff member left", "Staff & roles → turn off \"Can sign in\" for that person (they're signed out immediately). Check the Activity log to see who changed what. If payment or courier keys may be exposed, ask your developer to change them. A backup copy is made every night (Settings → Connected services & backups)."],
    bn: ["কিছু ভুল মনে হচ্ছে বা কোনো স্টাফ চলে গেছেন", "স্টাফ ও রোল → সেই ব্যক্তির \"সাইন ইন করতে পারবেন\" বন্ধ করুন (সাথে সাথে সাইন আউট হবেন)। কে কী বদলেছে তা কার্যক্রমের লগে দেখুন। পেমেন্ট বা কুরিয়ারের কী ফাঁস হতে পারে মনে হলে ডেভেলপারকে বদলাতে বলুন। প্রতি রাতে ব্যাকআপ কপি হয় (সেটিংস → সংযুক্ত সার্ভিস ও ব্যাকআপ)।"] },
];

export default function help(view) {
  view.innerHTML = String(html`<div class="page-head"><h1>${t("help")}</h1></div><p class="muted">${t("helpIntro")}</p>
    ${GUIDES.map((g) => { const [q, a] = g[lang()] ?? g.en; return html`<details class="card" style="padding:16px 20px"><summary style="font-weight:700;cursor:pointer;min-height:32px">${q}</summary><p style="margin:.6em 0 0">${a}</p></details>`; })}`);
}
